spring.application.name=find_band_room

#Server
server.port=8080
server.servlet.session.timeout=60m


#Database Properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/band_room_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=najeungyoon
spring.datasource.password=1717


#Mybatis Properties
# classpath = src/main/resources
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
